### ISSUE TITLE
running tests requires knowledge of the postgres password

### ISSUE THREAD

**Issue by jdkent** [PsychoinformaticsLab/neurostuff#14]
minor trip up for me when trying to run tests was not knowing to look for the [password here](https://github.com/PsychoinformaticsLab/neurostuff/blob/9b828d5ecd8dff928dcaa29af3da2c38a2759e85/.env.example#L3) in the instructions to create a test_db and run tests.

**Comment by adelavega** [comment]
yes, for some reason this wasn't an issue with neuroscout, but it is here. makes sense though. the db should have a password. 

can be fixed by editing the `example_config.py` to read `.env`
