### ISSUE TITLE
Alternative to flask-restful

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neurostuff#4]
Looks like we're using flask-restful for setting up API routes.

The project is pretty dead, and doesn't actually create any swagger-docs.

In fact, the author of the project even suggests alternative, as he himself uses other projects: https://github.com/flask-restful/flask-restful/issues/883

I say we abandon ship now, and get on something maintained, before we get in too deep. Even just using Flasks regular MethodView would work.

**Comment by jorgebg2016** [comment]
The thing I have to do is crying right now, because I was using flask-restful to build my API project. We can not always smile...

**Comment by tyarkoni** [comment]
On further investigation, this looks quite trivial. Connexion's `Resolver` is compatible with `MethodView` (example [here](https://github.com/zalando/connexion/tree/master/examples/openapi3/methodresolver)). So once we replace flask-restful's resourceful routing with MethodView, this is basically a drop-in replacement, and gives us all the benefits of connexion without having to do almost anything.

**Comment by adelavega** [comment]
I already made the switch so it should be pretty easy
